version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: products-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
